########### fun fact list
tips = [
    "Use reusable bags instead of plastic bags when shopping.",
    "Reduce water usage by fixing leaks and using water-saving appliances.",
    "Recycle paper, glass, and plastic to reduce waste.",
    "Switch to energy-efficient light bulbs and appliances.",
    "Plant trees and participate in tree-planting initiatives.",
    "Compost kitchen waste to reduce landfill contributions.",
    "Use public transportation, carpool, or bike to reduce carbon emissions.",
    "Turn off lights and electronics when not in use to save energy.",
    "Avoid single-use plastic products like straws and utensils.",
    "Participate in community clean-up events and initiatives.",
    "Conserve water by taking shorter showers and turning off the tap when not needed.",
    "Support local and sustainable products to reduce environmental impact.",
    "Educate others about the importance of environmental conservation.",
    "Dispose of electronic waste properly at designated recycling centers.",
    "Choose products with minimal packaging to reduce waste.",
    "Turn off the engine when parked to save fuel and reduce emissions.",
    "Opt for digital documents and emails to reduce paper usage.",
    "Use a reusable water bottle instead of disposable plastic bottles.",
    "Properly dispose of hazardous materials like batteries and chemicals.",
    "Install a programmable thermostat to optimize energy usage.",
    "Buy second-hand or repurpose items to reduce demand for new products.",
    "Avoid using pesticides and opt for natural alternatives in gardening.",
    "Conserve energy by air-drying clothes instead of using a dryer.",
    "Support and participate in local environmental initiatives and projects.",
    "Choose sustainably sourced and eco-friendly products.",
    "Properly dispose of medications to prevent water pollution.",
    "Practice responsible camping and hiking by leaving no trace.",
    "Reduce meat consumption and consider a plant-based diet.",
    "Properly maintain and service vehicles to improve fuel efficiency.",
    "Engage in eco-friendly activities like bird watching and nature walks.",
]
